# Generated by Django 3.2.6 on 2021-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.png', upload_to='laptops/pictures'),
        ),
    ]
