# Generated by Django 3.2.6 on 2021-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_comment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaerage_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
