# Generated by Django 3.2.6 on 2021-10-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_avaerage_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='avaerage_rating',
            new_name='average_rating',
        ),
    ]
