# Generated by Django 3.2.6 on 2021-10-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
